/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodtestapp;

import javax.swing.JOptionPane;

/**
 *
 * @author canno
 */
public class BloodTestGUI extends javax.swing.JFrame {
    private BloodTestScheduler<Patients> patientScheduler;
    /**
     * Creates new form BloodTestGUI
     */
    public BloodTestGUI() {
        initComponents();
        patientScheduler = new BloodTestScheduler<>();
    }
    
    public void displayAllPatients(String patientList) {//Display Patients to allPatientsTA
        allPatientsTA.setText(patientList);  
    }  
    
    public void displayFinalPatients(String finalPatientList) {//Display Patients to allPatientsTA
        priorityPatientTA.setText(finalPatientList);  
    } 
    
    public void displayFirstPatient(String firstPatient) {//Display Patients to allPatientsTA
        nextPatientTA.setText(firstPatient);  
    } 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        priorityPatientTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        allPatientsTA = new javax.swing.JTextArea();
        nextPatientLBL = new javax.swing.JLabel();
        allPatientsLBL = new javax.swing.JLabel();
        noShowLBL = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        noShowTA = new javax.swing.JTextArea();
        priorityPatientLBL = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        nextPatientTA = new javax.swing.JTextArea();
        prevBTN = new javax.swing.JButton();
        nextBTN = new javax.swing.JButton();
        addBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(153, 0, 51));
        titleLBL.setText("Blood Test Scheduler App");

        priorityPatientTA.setColumns(20);
        priorityPatientTA.setRows(5);
        jScrollPane1.setViewportView(priorityPatientTA);

        allPatientsTA.setColumns(20);
        allPatientsTA.setRows(5);
        jScrollPane2.setViewportView(allPatientsTA);

        nextPatientLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nextPatientLBL.setText("Next Patient:");

        allPatientsLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        allPatientsLBL.setText("All Patients:");

        noShowLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        noShowLBL.setText("No Shows:");

        noShowTA.setColumns(20);
        noShowTA.setRows(5);
        jScrollPane3.setViewportView(noShowTA);

        priorityPatientLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        priorityPatientLBL.setText("Patient Priority:");

        nextPatientTA.setColumns(20);
        nextPatientTA.setRows(5);
        jScrollPane4.setViewportView(nextPatientTA);

        prevBTN.setText("Prev");
        prevBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevBTNActionPerformed(evt);
            }
        });

        nextBTN.setText("Next");
        nextBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBTNActionPerformed(evt);
            }
        });

        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titleLBL)
                .addGap(421, 421, 421))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(priorityPatientLBL)
                        .addGap(556, 556, 556))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(allPatientsLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBTN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nextPatientLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prevBTN)
                        .addGap(18, 18, 18)
                        .addComponent(nextBTN)
                        .addGap(404, 404, 404))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(noShowLBL)
                        .addGap(196, 196, 196)))
                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(titleLBL)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextPatientLBL)
                    .addComponent(noShowLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prevBTN)
                    .addComponent(nextBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(priorityPatientLBL)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allPatientsLBL)
                    .addComponent(addBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prevBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevBTNActionPerformed
        // TODO add your handling code here:
        String prevPatient = patientScheduler.displayPrevPatient();
        nextPatientTA.setText(prevPatient);  
    }//GEN-LAST:event_prevBTNActionPerformed

    private void nextBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBTNActionPerformed
        // TODO add your handling code here:
        String nextPatient = patientScheduler.displayNextPatient();
        nextPatientTA.setText(nextPatient);
    }//GEN-LAST:event_nextBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        String name = JOptionPane.showInputDialog("Enter Patient's Name");
        int age = Integer.parseInt(JOptionPane.showInputDialog("Enter Age"));
        String priority = JOptionPane.showInputDialog("Enter Patient's Priority");
        String gpDetails = JOptionPane.showInputDialog("Enter Patient's GP Details");

        Patients patient = new Patients(name, age, priority, gpDetails);
        patientScheduler.push(patient); 
        
    }//GEN-LAST:event_addBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BloodTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BloodTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BloodTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BloodTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BloodTestGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JLabel allPatientsLBL;
    private javax.swing.JTextArea allPatientsTA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton nextBTN;
    private javax.swing.JLabel nextPatientLBL;
    public static javax.swing.JTextArea nextPatientTA;
    private javax.swing.JLabel noShowLBL;
    private javax.swing.JTextArea noShowTA;
    private javax.swing.JButton prevBTN;
    private javax.swing.JLabel priorityPatientLBL;
    private javax.swing.JTextArea priorityPatientTA;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables

}
